trigger: none
pool: 'My First Agent'

variables:
  akansha_path: '$(System.DefaultWorkingDirectory)/terraform.tfvars'
  service_connection: 'Azure Service Connection'


steps:

- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: $(akansha_path)
    backendServiceArm: $(service_connection)
    backendAzureRmOverrideSubscriptionID: '9f199aee-1ad7-464f-bd74-4b88ef990086'
    backendAzureRmResourceGroupName: 'akansha-rg'
    backendAzureRmStorageAccountName: 'akanshakastorage'
    backendAzureRmContainerName: 'akanshacontainer'
    backendAzureRmKey: 'tfstatefile'

- task: TerraformTask@5
  displayName: Terraform Validate
  inputs:
    provider: 'azurerm'
    command: 'validate'

- task: TerraformTask@5
  displayName: Terraform Fmt
  inputs:
    provider: 'azurerm'
    command: 'custom'
    outputTo: 'console'
    customCommand: 'fmt'
    environmentServiceNameAzureRM: $(service_connection)
    environmentAzureRmOverrideSubscriptionID: '9f199aee-1ad7-464f-bd74-4b88ef990086'

- task: TerraformTask@5
  displayName: Terraform Plan
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: $(akansha_path)
    environmentServiceNameAzureRM: $(service_connection)
    environmentAzureRmOverrideSubscriptionID: '9f199aee-1ad7-464f-bd74-4b88ef990086'