trigger: none
pool: 'My First Agent'
steps:

- task: TerraformInstaller@1
  displayName: Terraform Install
  inputs:
    terraformVersion: '1.12.2'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
    backendServiceArm: 'My First SC'
    backendAzureRmOverrideSubscriptionID: '9f199aee-1ad7-464f-bd74-4b88ef990086'
    backendAzureRmResourceGroupName: 'akansha-rg'
    backendAzureRmStorageAccountName: 'akanshakastorage'
    backendAzureRmContainerName: 'akanshacontainer'
    backendAzureRmKey: 'akansha.tfstate'
